<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/gallery.php");
	include("$currDir/gallery_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('gallery');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "gallery";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`gallery`.`id`" => "id",
		"`gallery`.`title`" => "title",
		"IF(    CHAR_LENGTH(`gallery_categories1`.`name`), CONCAT_WS('',   `gallery_categories1`.`name`), '') /* Category */" => "category",
		"`gallery`.`tags`" => "tags",
		"`gallery`.`content`" => "content",
		"`gallery`.`photo`" => "photo",
		"if(`gallery`.`date`,date_format(`gallery`.`date`,'%m/%d/%Y'),'')" => "date",
		"`gallery`.`author`" => "author",
		"`gallery`.`posted`" => "posted"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`gallery`.`id`',
		2 => 2,
		3 => '`gallery_categories1`.`name`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`gallery`.`date`',
		8 => 8,
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`gallery`.`id`" => "id",
		"`gallery`.`title`" => "title",
		"IF(    CHAR_LENGTH(`gallery_categories1`.`name`), CONCAT_WS('',   `gallery_categories1`.`name`), '') /* Category */" => "category",
		"`gallery`.`tags`" => "tags",
		"`gallery`.`content`" => "content",
		"`gallery`.`photo`" => "photo",
		"if(`gallery`.`date`,date_format(`gallery`.`date`,'%m/%d/%Y'),'')" => "date",
		"`gallery`.`author`" => "author",
		"`gallery`.`posted`" => "posted"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`gallery`.`id`" => "ID",
		"`gallery`.`title`" => "Title",
		"IF(    CHAR_LENGTH(`gallery_categories1`.`name`), CONCAT_WS('',   `gallery_categories1`.`name`), '') /* Category */" => "Category",
		"`gallery`.`tags`" => "Tags",
		"`gallery`.`content`" => "Content",
		"`gallery`.`date`" => "Date",
		"`gallery`.`author`" => "Author",
		"`gallery`.`posted`" => "Status"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`gallery`.`id`" => "id",
		"`gallery`.`title`" => "title",
		"IF(    CHAR_LENGTH(`gallery_categories1`.`name`), CONCAT_WS('',   `gallery_categories1`.`name`), '') /* Category */" => "category",
		"`gallery`.`tags`" => "tags",
		"`gallery`.`content`" => "content",
		"if(`gallery`.`date`,date_format(`gallery`.`date`,'%m/%d/%Y'),'')" => "date",
		"`gallery`.`author`" => "author",
		"`gallery`.`posted`" => "posted"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'category' => 'Category');

	$x->QueryFrom = "`gallery` LEFT JOIN `gallery_categories` as gallery_categories1 ON `gallery_categories1`.`id`=`gallery`.`category` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "gallery_view.php";
	$x->RedirectAfterInsert = "gallery_view.php?SelectedID=#ID#";
	$x->TableTitle = "gallery";
	$x->TableIcon = "resources/table_icons/feed.png";
	$x->PrimaryKey = "`gallery`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Title", "Category", "Tags", "Content", "Photo", "Date", "Author", "Status");
	$x->ColFieldName = array('title', 'category', 'tags', 'content', 'photo', 'date', 'author', 'posted');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/gallery_templateTV.html';
	$x->SelectedTemplate = 'templates/gallery_templateTVS.html';
	$x->TemplateDV = 'templates/gallery_templateDV.html';
	$x->TemplateDVP = 'templates/gallery_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `gallery`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='gallery' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `gallery`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='gallery' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`gallery`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: gallery_init
	$render=TRUE;
	if(function_exists('gallery_init')){
		$args=array();
		$render=gallery_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: gallery_header
	$headerCode='';
	if(function_exists('gallery_header')){
		$args=array();
		$headerCode=gallery_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: gallery_footer
	$footerCode='';
	if(function_exists('gallery_footer')){
		$args=array();
		$footerCode=gallery_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>